Problem: loading extension library fails
```
ERROR:  could not load library "examples/is_zero/target/release/libis_zero.dylib":
dlopen(examples/is_zero/target/release/libis_zero.dylib, 10): Library not loaded: @rpath/libstd-34de3979baa7a8ad.dylib
```

Solution: currently, the library is built as a dylib, and therefore does
not bundle Rust libraries; changing the target extension to cdylib crate
type and the main library to rlib alleviates the problem.